# Generated by Django 4.2.5 on 2023-11-29 03:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_remove_user_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("experiment_name", models.CharField(max_length=255)),
                ("metric_name", models.CharField(max_length=255)),
                ("result_data", models.JSONField()),
            ],
        ),
    ]
