# Generated by Django 4.2.5 on 2023-11-29 03:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_testresult"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="testresult",
            table="test_results",
        ),
    ]
